# Generated by Django 5.2 on 2025-04-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
