# Generated by Django 5.2 on 2025-04-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_options_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('responsible', models.CharField(choices=[('Mara Ferreira', 'Mara Ferreira'), ('Aline Zampa', 'Aline Zampa')], max_length=50, verbose_name='Responsible Person')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.client', verbose_name='Client')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
